/**
 * The API surface the React layer talks to. Implemented by `PdfEditorEngine`
 * in `src/core/engine.ts`; declared separately so the UI can be written and
 * type-checked against a stable contract.
 */
import type {
  DocumentWarning,
  EditStats,
  EditableDocument,
  LineEdit,
} from './model'

export interface RenderResult {
  width: number
  height: number
  /** Device-pixel-ratio-aware scale actually used. */
  scale: number
}

export interface MeasureResult {
  /** Width of the proposed text in page-space units. */
  width: number
  /** Width of the original line, for comparison. */
  originalWidth: number
  /** True when the new text fits in the original advance. */
  fits: boolean
  /** Characters that the original font cannot encode. */
  unmapped: string[]
  /** True when a fallback font would have to be embedded. */
  needsFallback: boolean
}

export interface ExportResult {
  bytes: Uint8Array
  stats: EditStats
  warnings: DocumentWarning[]
}

export interface EditorEngine {
  readonly document: EditableDocument
  readonly fileName: string

  /** Render a page into a canvas at `scale` CSS-pixels per point. */
  renderPage(
    pageIndex: number,
    scale: number,
    canvas: HTMLCanvasElement,
    signal?: AbortSignal
  ): Promise<RenderResult>

  /** Cheap, synchronous width/encodability check used for live UI feedback. */
  measureLine(lineId: string, text: string): MeasureResult

  /** Produce the edited PDF. */
  export(edits: ReadonlyMap<string, LineEdit>): Promise<ExportResult>

  /**
   * Re-render one page through the real export pipeline, so the preview is
   * generated by exactly the code path that produces the download.
   */
  renderEditedPage(
    pageIndex: number,
    edits: ReadonlyMap<string, LineEdit>,
    scale: number,
    canvas: HTMLCanvasElement,
    signal?: AbortSignal
  ): Promise<RenderResult>

  destroy(): void
}
